DELETE http://localhost:3003/api/blogs/60b9c4a9e1a8b054720d309f
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imthbm5hbmExIiwiaWQiOiI2MGI5M2E2ZDNkOWI3MjJkYzE3ZGNjMmMiLCJpYXQiOjE2MjI3NzUyNjh9.AjRrWng0KWKRIhYSTXwnQIJ6mOfz0B7b5ZWq7GRpMUY

{
    "id": "60b9c4a9e1a8b054720d309f"
}