POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjkzYTRlM2Q5YjcyMmRjMTdkY2MyYiIsImlhdCI6MTYyMjc4ODExN30.0_IYTth65wcXkm3uqhUykHgMs7iainoHORig7m8opgI

{
    "title": "Posting a blog after modifying utils/middleware.errorHandler to handle JsonWebTokenError",
    "url": "https://errorHandler.com/JsonWebTokenError",
    "author": "Superuser",
    "likes": 2
}